# Generated by Django 5.1.15 on 2026-07-24 15:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='釣り場名')),
                ('prefecture', models.CharField(choices=[('Kanagawa', '神奈川'), ('Tokyo', '東京')], db_index=True, verbose_name='都道府県名')),
                ('city', models.CharField(max_length=50, verbose_name='市区町村')),
                ('address', models.CharField(max_length=200, verbose_name='住所')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='位置情報')),
                ('warter_type', models.CharField(choices=[('sea', '海'), ('river', '河川'), ('lake', '湖')], verbose_name='種別')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='作成日')),
                ('update_at', models.DateTimeField(blank=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '釣り場',
                'verbose_name_plural': '釣り場',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='駐輪場名')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='位置情報')),
                ('motorcycle_allowed', models.BooleanField(db_index=True, verbose_name='バイク駐車可否')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='バイク駐車可能台数')),
                ('is_free', models.BooleanField(default=True, verbose_name='無料')),
                ('fee_note', models.CharField(blank=True, max_length=200, verbose_name='料金備考')),
                ('distance_to_spot_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='釣り場までの距離(m)')),
                ('note', models.TextField(blank=True, verbose_name='備考(規制情報など)')),
                ('spot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_lots', to='spots.fishingspot', verbose_name='釣り場')),
            ],
            options={
                'verbose_name': '駐車場',
                'verbose_name_plural': '駐車場',
            },
        ),
    ]
