# Generated by Django 5.1.15 on 2026-07-26 16:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinglot',
            old_name='spot_id',
            new_name='spot',
        ),
        migrations.RemoveField(
            model_name='fishingspot',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='fishingspot',
            name='warter_type',
        ),
        migrations.AddField(
            model_name='fishingspot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fishingspot',
            name='water_type',
            field=models.CharField(choices=[('sea', '海'), ('river', '河川'), ('lake', '湖')], db_index=True, default='sea', max_length=10, verbose_name='種別'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fishingspot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fishingspot',
            name='prefecture',
            field=models.CharField(choices=[('kanagawa', '神奈川県'), ('tokyo', '東京都')], db_index=True, default='kanagawa', max_length=20, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='位置情報'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='name',
            field=models.CharField(max_length=100, verbose_name='駐車場名'),
        ),
    ]
